/*********************************************************************************************
Copyright © 2020 DuPont. All rights reserved. 
Author: Rajan Kumar Mishra
Email: rajankumar.mishra@tcs.com
Last Modified Date : 26th Feb 2020
Description: This is constant class which we are using for keeping constant values for PostRefreshClusterUpdate requirement
**********************************************************************************************/
global class ConstantsUtil {
	public final string CLUSTER_VALUE_P23 = 'P23';
    public final string CLUSTER_VALUE_Q23 = 'Q23';
    public final string EXTERNAL_ERP_ID_STARTS_WITH = '%P23%';
}