/*
 * Name		 :   PAServiceState_UT
 * Description  :   This is the test class for PAServiceState
 * Author	   :   Infosys Limited
 * Created Date :   21-03-2013
 *
 * Version	  Modified Date	   Modified By	 Modification
 * ------------------------------------------------------------------------------
 */
@isTest
private class PAServiceState_UT {
	static testMethod void paServiceStateTestMethod() {
		PAServiceState PAServiceState1 = new PAServiceState();
	}
}